"""
PDF Generator — Creates downloadable PDF research reports using FPDF2.
Returns bytes suitable for st.download_button.
"""

from datetime import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos
import re


class ResearchPDF(FPDF):
    """Custom FPDF subclass with header and footer."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_fill_color(15, 15, 35)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, "ResearchMind", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True, align="C")
        self.set_text_color(160, 160, 200)
        self.set_font("Helvetica", "", 9)
        self.cell(
            0, 7,
            f"AI-Powered Research Report  |  Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C"
        )
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 150)
        self.cell(0, 10, "Generated by ResearchMind  |  AI Research Assistant", align="C")


def _clean_markdown(text: str) -> str:
    """Strip markdown syntax for plain-text PDF output."""
    text = re.sub(r"#{1,6}\s*", "", text)          # headings
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)   # bold
    text = re.sub(r"\*(.+?)\*", r"\1", text)        # italic
    text = re.sub(r"`(.+?)`", r"\1", text)          # inline code
    text = re.sub(r"\[(.+?)\]\((.+?)\)", r"\1 (\2)", text)  # links
    text = re.sub(r"---+", "", text)                # horizontal rules
    return text.strip()


def _section_header(pdf: FPDF, title: str):
    """Render a styled section header."""
    pdf.set_fill_color(25, 25, 60)
    pdf.set_text_color(180, 180, 255)
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 9, f"  {title}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
    pdf.set_text_color(30, 30, 30)
    pdf.ln(2)


def _body_text(pdf: FPDF, text: str):
    """Render body text, handling encoding safely."""
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    clean = _clean_markdown(text)
    # Encode safely — FPDF latin-1 subset
    safe = clean.encode("latin-1", errors="replace").decode("latin-1")
    pdf.multi_cell(0, 6, safe)
    pdf.ln(2)


def generate_pdf(response_dict: dict) -> bytes:
    """
    Generate a PDF research report from the agent's response dict.

    Args:
        response_dict: Dict returned by ResearchAgent.run(), containing:
            - report (str): Full markdown report
            - sources (list): Scored source dicts
            - sub_questions (list): 3 sub-questions researched
            - sections (dict): Parsed report sections
            - is_followup (bool)
            - elapsed_sec (float)

    Returns:
        PDF as bytes for st.download_button
    """
    pdf = ResearchPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    sections = response_dict.get("sections", {})
    sources = response_dict.get("sources", [])
    sub_questions = response_dict.get("sub_questions", [])
    is_followup = response_dict.get("is_followup", False)

    # ── Query Box ─────────────────────────────────────────────────────────
    _section_header(pdf, "Research Query")
    pdf.set_fill_color(240, 240, 255)
    pdf.set_text_color(20, 20, 60)
    pdf.set_font("Helvetica", "B", 10)

    # Pull original query from first sub_question context or sections
    query_text = response_dict.get("query", "Research Query")
    safe_query = query_text.encode("latin-1", errors="replace").decode("latin-1")
    pdf.multi_cell(0, 8, f"  {safe_query}", fill=True)
    pdf.ln(4)

    # ── Sub-Questions ─────────────────────────────────────────────────────
    if sub_questions and not is_followup:
        _section_header(pdf, "Sub-Questions Researched")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        for i, sq in enumerate(sub_questions, 1):
            safe_sq = sq.encode("latin-1", errors="replace").decode("latin-1")
            pdf.multi_cell(0, 6, f"  {i}. {safe_sq}")
        pdf.ln(3)

    # ── Executive Summary ─────────────────────────────────────────────────
    exec_summary = sections.get("executive_summary", "")
    if exec_summary:
        _section_header(pdf, "Executive Summary")
        _body_text(pdf, exec_summary)

    # ── Key Findings ──────────────────────────────────────────────────────
    key_findings = sections.get("key_findings", "")
    if key_findings:
        _section_header(pdf, "Key Findings")
        # Render each bullet as numbered line
        lines = [l.strip() for l in key_findings.split("\n") if l.strip()]
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        count = 1
        for line in lines:
            # Strip leading markdown bullet characters
            clean_line = re.sub(r"^[-*•]\s*", "", line)
            clean_line = _clean_markdown(clean_line)
            safe_line = clean_line.encode("latin-1", errors="replace").decode("latin-1")
            if safe_line:
                pdf.multi_cell(0, 6, f"  {count}. {safe_line}")
                count += 1
        pdf.ln(3)

    # ── Deep Analysis ─────────────────────────────────────────────────────
    deep_analysis = sections.get("deep_analysis", "")
    if deep_analysis:
        _section_header(pdf, "Deep Analysis")
        _body_text(pdf, deep_analysis)

    # ── Conflicting Viewpoints ────────────────────────────────────────────
    conflicts = sections.get("conflicting_viewpoints", "")
    if conflicts:
        _section_header(pdf, "Conflicting Viewpoints")
        _body_text(pdf, conflicts)

    # ── Knowledge Gaps ────────────────────────────────────────────────────
    gaps = sections.get("knowledge_gaps", "")
    if gaps:
        _section_header(pdf, "Knowledge Gaps")
        _body_text(pdf, gaps)

    # ── Source Table ──────────────────────────────────────────────────────
    if sources:
        _section_header(pdf, "Sources & Credibility Scores")

        # Table header
        pdf.set_fill_color(40, 40, 80)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 9)
        col_widths = [70, 80, 20]
        pdf.cell(col_widths[0], 8, "Title", border=1, fill=True)
        pdf.cell(col_widths[1], 8, "URL", border=1, fill=True)
        pdf.cell(col_widths[2], 8, "Score", border=1, fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Table rows
        pdf.set_font("Helvetica", "", 8)
        for i, source in enumerate(sources):
            fill = i % 2 == 0
            pdf.set_fill_color(245, 245, 255) if fill else pdf.set_fill_color(255, 255, 255)
            pdf.set_text_color(30, 30, 60)

            title = source.get("title", "Untitled")[:45]
            url = source.get("url", "")[:55]
            score = str(round(source.get("credibility_score", 0), 1))

            safe_title = title.encode("latin-1", errors="replace").decode("latin-1")
            safe_url = url.encode("latin-1", errors="replace").decode("latin-1")

            pdf.cell(col_widths[0], 7, safe_title, border=1, fill=fill)
            pdf.cell(col_widths[1], 7, safe_url, border=1, fill=fill)
            pdf.cell(col_widths[2], 7, score, border=1, fill=fill, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.ln(4)

    return bytes(pdf.output())
